name: Publish prerelease libraries

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  placeholder:
    name: Not supported on this branch
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Not supported"
          exit 1
